[tool.black]
line-length = 79
target_version = ['py37']

[tool.isort]
multi_line_output = 3
force_single_line = true
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 79
known_typing_library = '''
    typing,
    typing_extensions,
'''
sections = '''
    FUTURE,
    TYPING_LIBRARY,
    STDLIB,
    THIRDPARTY,
    FIRSTPARTY,
    LOCALFOLDER
'''